export const SET_SINGER = 'SET_SINGER';

export const SET_PLAYING = 'SET_PLAYING';

export const SET_FULLSCREEN = 'SET_FULLSCREEN';

export const SET_PLAYLIST = 'SET_PLAYLIST';

export const SET_SEQUENCELIST = 'SET_SEQUENCELIST';

export const SET_PLAYMODE = 'SET_PLAYMODE';

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX';

export const SET_MUSICMENU = 'SET_MUSICMENU';

export const SET_QUERY = 'SET_QUERY';

export const SET_SINGERBACKROUTE = 'SET_SINGERBACKROUTE';

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY';

export const SET_FAVORITELIST = 'SET_FAVORITELIST';

export const SET_RECENTPLAYLIST = 'SET_RECENTPLAYLIST';

export const SET_SHOWSONGCOMMENT = 'SET_SHOWSONGCOMMENT';

export const SET_SHOWMENUCOMMENT = 'SET_SHOWMENUCOMMENT';

export const SET_BLURINPUT = 'SET_BLURINPUT';
